version: "3.8"
services:
  frontend:
    container_name: movie-project-frontend
    image: kelvin2kk/cinema-frontend:latest
    restart: always
    networks:
      - cinema-project

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    env_file:
      - .env
    ports:
      - "3308:3306"
    volumes:
      - movie_project_volume:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - cinema-project

  node:
    depends_on:
      - mysql_db
    container_name: movie-project-backend
    image: kelvin2kk/cinema-backend:latest
    restart: always
    env_file:
      - .env
    networks:
      - cinema-project

  caddy:
    image: caddy:2-alpine
    container_name: caddy_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - cinema-project

volumes:
  movie_project_volume:
  caddy_data:
  caddy_config:

networks:
  cinema-project: