- name: Install VPS
  hosts: list_host
  become: true
  vars_files:
    - secrets.yml
  tasks:
    - name: setup docker
      apt:
        name: docker.io
        state: present

    - name: setup docker-compose
      shell: curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      args:
        creates: /usr/local/bin/docker-compose

    - name: Grant permissive execution to docker-compose
      file:
        path: /usr/local/bin/docker-compose
        mode: '0700'

    - name: Create project directory
      file:
        path: /root/MovieTheater_Project
        state: directory
        mode: '0755'

    - name: Copy docker-compose file
      copy:
        src: docker-compose.yml
        dest: /root/MovieTheater_Project/docker-compose.yml

    - name: Generate runtime env file
      template:
        src: .env_project.j2
        dest: /root/MovieTheater_Project/.env

    - name: Copy db-init directory
      copy:
        src: db-init
        dest: /root/MovieTheater_Project/
        mode: '0755'
        directory_mode: '0755'

    - name: Copy Caddyfile
      copy:
        src: Caddyfile
        dest: /root/MovieTheater_Project/Caddyfile

    - name: Apply new docker-compose configuration
      shell: |
        docker-compose down
        docker-compose up -d --remove-orphans
      args:
        chdir: /root/MovieTheater_Project
