name: Infrastructure and App Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy_all:
    runs-on: ubuntu-latest
    
    env:
      TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
      TF_VAR_ssh_key: ${{ secrets.SSH_KEY_ID }}
      TF_VAR_github_access_token: ${{ secrets.GH_ACCESS_TOKEN }}
      ANSIBLE_HOST_KEY_CHECKING: "False"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.8

      - name: Terraform Init and Apply
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_ACCESS_KEY }}
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Setup Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Create SSH Key and Vault Password
        working-directory: ./ansible
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh-key-do
          chmod 600 ssh-key-do
          echo "${{ secrets.VAULT_PASSWORD }}" > vault_pass.txt

      - name: Run Ansible Playbook For Project
        working-directory: ./ansible
        run: |
          ansible-playbook -i hosts.ini install_vps.yml --vault-password-file vault_pass.txt
          
      - name: Get Project VPS IP
        id: get_ip
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_ACCESS_KEY }}
        run: |
          PROJECT_IP=$(terraform output -raw project_vps_ip)
          echo "PROJECT_VPS_IP=$PROJECT_IP" >> $GITHUB_ENV

      - name: Run Ansible Playbook For Monitoring
        working-directory: ./ansible
        run: |
          ansible-playbook -i hosts-monitoring.ini monitoring/install_vps_monitoring.yml \
            --extra-vars "project_vps_ip=${{ env.PROJECT_VPS_IP }} telegram_token=${{ secrets.TELEGRAM_TOKEN }} telegram_bot_id=${{ secrets.TELEGRAM_BOT_ID }}"